# Generated by Django 3.0.7 on 2020-07-16 07:37

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('banner', models.CharField(default='https://i.ibb.co/kDcGv5D/sb-blog-programming.jpg', max_length=1000)),
                ('content', martor.models.MartorField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
