# Generated by Django 3.0.7 on 2020-06-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200626_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('start', models.CharField(max_length=10)),
                ('present', models.BooleanField(blank=True, default=False, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('start', models.CharField(max_length=10)),
                ('present', models.BooleanField(blank=True, default=False, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
    ]
